# Generated by Django 5.2 on 2025-05-14 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='economic_code',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='کد اقتصادی خریدار'),
        ),
        migrations.AddField(
            model_name='customer',
            name='national_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='شناسه ملی خریدار'),
        ),
        migrations.AddField(
            model_name='customer',
            name='postcode',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='کد پستی خریدار'),
        ),
    ]
