# Generated by Django 5.2 on 2025-05-12 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_sales_customer_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='buyer_economic_code',
            new_name='economic_code',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='buyer_national_id',
            new_name='national_id',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='buyer_postcode',
            new_name='postcode',
        ),
    ]
