# Generated by Django 5.2 on 2025-05-13 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_alter_invoice_options_remove_invoice_queue_and_more'),
        ('myapp', '0003_rename_buyer_economic_code_customer_economic_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='shipment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice', to='myapp.shipments'),
        ),
    ]
