# Generated by Django 5.2 on 2025-05-13 11:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_alter_invoice_shipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='havaleh_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='havaleh_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoice',
            name='havaleh_serial',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Havaleh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('serial', models.CharField(max_length=255, unique=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='havaleh', to='invoice.invoice')),
            ],
            options={
                'verbose_name': 'Havaleh',
                'verbose_name_plural': 'Havalehs',
                'db_table': 'Havaleh',
            },
        ),
        migrations.CreateModel(
            name='HavalehItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('gsm', models.CharField(blank=True, max_length=50, null=True)),
                ('width', models.CharField(blank=True, max_length=50, null=True)),
                ('buyer', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity', models.IntegerField(default=1)),
                ('weight', models.FloatField(default=0)),
                ('havaleh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='invoice.havaleh')),
            ],
            options={
                'verbose_name': 'Havaleh Item',
                'verbose_name_plural': 'Havaleh Items',
                'db_table': 'HavalehItem',
            },
        ),
    ]
